### ISSUE TITLE
skos:prefLabel / skos:porefLabel

### ISSUE THREAD

**Issue by rowan-ardc** [frmichel/taxref-ld#1]
Hi - I noticed a minor error in the following - "skos:porefLabel"

<http://taxref.mnhn.fr/lod/taxon/349525/10.0>
  a owl:Class;
  rdfs:label "Biota";
  skos:porefLabel "Biota";
  taxrefprop:hasReferenceName <http://taxref.mnhn.fr/lod/name/349525>;
.

**Comment by frmichel** [comment]
Hi @rowan-ardc, good catch, thx!

I fixed it and committed a few other minor changes. I had actually fixed it in the version online, when you directly lookup the URIs.

Also if you are interested, I committed taxref10.zip that contains the whole dataset with concepts and classes.

Franck.
