### ISSUE TITLE
Add data from CatMiNat

### ISSUE THREAD

**Issue by jmvanel** [frmichel/taxref-ld#12]
[CatMiNat](http://philippe.julve.pagesperso-orange.fr/catminat.htm) (alias Catalogue des Milieux Naturels) is a tabular dataset having a good reputation among botanists . 
Here is the complete list of headers; the ones particularly interesting for me are in bold:
   
rang_taxinomique | N°_Taxinomique_BDNFF | **N°_Nomenclatural_BDNFF** | code_CATMINAT | julve: version fichier : 15 novembre 2020 Nom scientifique : BDTFX version 6.00 du « 27 septembre 2019 », Flora Gallica et The Plant List licence ODBL 		NOM_SCIENTIFIQUE | **CHOROLOGIE** | **inflorescence** | **sexualité** | **ordre_maturation** | **pollinisation** | **fruit** | **dissémination** | **couleur_fleur** | macule | **floraison** | type_ligneux | Hauteur_végétative_maximum_[m] | TYPE_BIOLOGIQUE | FORMATION_VEGETALE | **CARACTERISATION_ECOLOGIQUE_(HABITAT_OPTIMAL)** | **INDICATION_PHYTOSOCIOLOGIQUE_CARACTERISTIQUE** | INDICATION_CARACTERISTIQUE_TRANSGRESSIVE | INDICATION_DIFFERENTIELLE_1 | INDICATION_DIFFERENTIELLE_2 | INDICATION_DIFFERENTIELLE_3 | **Lumière | Température | Continentalité | Humidité_atmosphérique | Humidité_édaphique | Réaction_du_sol_(pH) | Niveau_trophique | Salinité | Texture | Matière_organique** | Lichtzahl | Temperaturzahl | Kontinentalität | Feuchtzahl | Reaktionszahl | Nutrients | Salz | CLASSE_(-opsida) | pjulve: d'après APG III 2009 et Christenhusz & al. 2011a&b pour les gymnospermes et les fougères 		SUBCLASSE_(-idae) | pjulve: d'après APG IV 2016 		Clade_intermédiaire | pjulve: d'après Chase & Reveal 2009 (basé sur APG III 2009, mais encore utilisable sur APG IV d'après ses auteurs)  		SUPERORDRE_(-anae) | pjulve: d'après APG IV 2016 		Clade_intermédiaire | pjulve: d'après APG IV 2016 		Clade_intermédiaire | pjulve: d'après APG IV 2016 		Clade_intermédiaire | pjulve: d'après APG IV 2016  		ORDRE_(-ales) | pjulve: [d'après APG IV, 2016  		FAMILLE_(-aceae) | numSpA | numSpB | numSpH | nomA | nomB | nomH

NOTES
- it should be easy to integrate, thanks to  column N°_Nomenclatural_BDNFF , which is http://www.wikidata.org/prop/direct/P3105 (Tela Botanica ID)
- AFAIK the file is updated without notice, so a way to get the timestamp is HTTP:
```
wget --method=head --debug http://philippe.julve.pagesperso-orange.fr/baseflor.xlsx
...
HTTP/1.1 200 OK
Date: Sun, 13 Feb 2022 07:28:22 GMT
Server: Apache
X-Mod-ppHosting: v5.0.0
Last-Modified: Wed, 17 Feb 2021 11:09:43 GMT
ETag: "307ef7-5bb8641880d43"
Accept-Ranges: bytes
Content-Length: 3178231
Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
```

**Comment by frmichel** [comment]
Bonjour Jean-Marc, thx for the info.

In TAXREF-LD we generate links based on what is available through TAXREF's API. So I'll et the MNHN know about this and let them decide whether they want to include these ids in the TAXREF distribution.

Franck.
