### ISSUE TITLE
Change of reference

### ISSUE THREAD

**Issue by Archilegt** [frmichel/taxref-ld#13]
In:
TAXREF-LD: Knowledge Graph of the French taxonomic registery. Franck Michel, Catherine FARON, Sandrine TERCERIE, Olivier GARGOMINY. 2017-2022. https://doi.org/10.5281/zenodo.5848916

please change "French taxonomic registery" to "French Taxonomic Register".

Also, keep me in the loop when updates are needed for the classification and species of Myriapoda and Onychophora. I will help if I can.

**Comment by frmichel** [comment]
Hi @Archilegt, thx for the notice.
The use of register vs. registry seems to depend on people's personal preference. I've seen registry used quite often (e.g. https://doi.org/10.1080/10635150500541680, https://cetaf.org/registry-of-collections/), but there are examples with register too. As a non-native English speaker I can't really decide, so I tend to follow the (apparent) majority.

> keep me in the loop when updates are needed for the classification and species of Myriapoda and Onychophora. I will help if I can.

I'm the author of the RDF version but I'm not a biologist. The source data is that of TAXREF which is maintained but the Museum of Natural History of Paris (https://inpn.mnhn.fr/programme/referentiel-taxonomique-taxref?lg=en). You can reach out to them.
