### ISSUE TITLE
Using URIs instead of blank nodes for images

### ISSUE THREAD

**Issue by freddylimpens** [frmichel/taxref-ld#6]
For instance doing :
<http://taxref.mnhn.fr/lod/taxon/100128/12.0> foaf:depiction <https://taxref.mnhn.fr/api/media/257061> .

**Comment by frmichel** [comment]
Added in commit https://github.com/frmichel/taxref-ld/commit/48d6fa15b69b2039366bbe4876a48212572b9285

**Comment by jmvanel** [comment]
I see that it's already in line :

Asparagus officinalis
<https://semantic-forms.cc:1953/ldp/1594118550413-10980173898220343>  = <
https://semantic-forms.cc:1953/ldp/1594118550413-10980173898220343>


Jean-Marc Vanel
<http://semantic-forms.cc:9112/display?displayuri=http://jmvanel.free.fr/jmv.rdf%23me>
+33
(0)6 89 16 29 52


Le mar. 7 juil. 2020 à 12:15, Franck Michel <notifications@github.com> a
écrit :

**Comment by frmichel** [comment]
Yes, updated it this morning ;)
