### ISSUE TITLE
Pointing Taxref "propertyURI" and "valueURI" in EML document

### ISSUE THREAD

**Issue by yvanlebras** [frmichel/taxref-ld#9]
Hi amazing taxrel-ld team ;) ,

Hope all is ok on your side!

We (PNDB team) are finally trying "eml-semantics" module us to annotate EML metadata documents (you can look at our test data/metadata portal instance for a first try for Esp attribute of this document https://data.test.pndb.fr/view/urn%3Auuid%3Abba27b7c-112b-4f86-81ea-1db69aab3301 ) and I want to add real relevant information. So for example on this same document, for Esp attribute, author indicated "Species name, following TaxRef vXX nomenclature (https://inpn.mnhn.fr/programme/referentiel-taxonomique-taxref)" and I want to try to use taxref terminological resources so we can provide a "propertyURI" and "valueURI" from taxref to describe the fact this attribute is populated by a species name as we can find in taxref).
Can you help me to know if this is possible and what can be the URI and reltaed terms ?
Wishing you a good week-end,
Best,
Yvan

**Comment by yvanlebras** [comment]
Apparently  http://taxref.mnhn.fr/lod/taxon/$1/13.0 is an URI we can use to indicate CD_NOM looking at https://www.wikidata.org/wiki/Property:P3186

**Comment by frmichel** [comment]
Salut Yvan,

Indeed TAXREF taxon URIs are formed as `http://taxref.mnhn.fr/lod/taxon/TAXON_ID/TAXREF_VERSION` where TAXON_ID is the CD_NOM and TAXREF_VERSION is 13.0, 12.0 etc.
Example: taxref.mnhn.fr/lod/taxon/60878/13.0

Then, a taxon (an OWL class in TAXREF-LD) has an rdfs:label which is the reference name without the authority.
More formally, it has a reference name (http://taxref.i3s.unice.fr/lod/property/hasReferenceName) whose prefLabel is the preferred scientific name. So you can submit this SPARQL query to http://taxref.mnhn.fr/sparql:

```sparql
select distinct * where {
  ?t <http://taxref.mnhn.fr/lod/property/hasReferenceName> [
       skos:prefLabel "Delphinus delphis";
  ]
}
```

If you want only the one in TAXREF v13, then:
```sparql
select distinct * where {
  ?t <http://taxref.mnhn.fr/lod/property/hasReferenceName> [
       skos:prefLabel "Delphinus delphis";
    ];
    rdfs:isDefinedBy <http://taxref.mnhn.fr/lod/taxref-ld/13.0>
}
```

Note that if you don't wanna use SPARQL you can do the same kind of thing with the TAXREF API: https://taxref.mnhn.fr/taxref-web/api/doc

Does it answer you question?

**Comment by yvanlebras** [comment]
Thank you Franck!

Your answer help me to see "pointers" I can use thanks! My question is here more general and not for example linked to a specific species. If I have to specify / point a taxref term through an URI, where can I find this URI ? For my example, I serach to give a "valueURI" for "scientific name", same for "Taxonomic family" and "Taxonomic gender". Not sure this is understandable, sorry ;) 
To give an example, to mention on our metadata document "Plant Cover Percentage" ""meaning"" / "term", we can use valueURI label="Plant Cover Percentage">http://purl.dataone.org/odo/ECSO_00001197</valueURI.

Thank you for your help!

**Comment by frmichel** [comment]
You can have a look at the Github repo itself:
- in https://github.com/frmichel/taxref-ld/tree/master/dataset you can see all files Taxrefld_static_*.ttl: these give the definitions of the properties, taxonomic ranks, habitats, statuses etc. => I think that's where you might find what you look for.
- in https://github.com/frmichel/taxref-ld/tree/master/dataset/examples you can see examples of how these properties and concepts are used concretely to describe a taxon and its names, statues, etc.

Let me know whether it helps.
